### ISSUE TITLE
Building a lighter version

### ISSUE THREAD

**Issue by dobromir-hristov** [xkjyeah/vue-google-maps#171]
So I did a fork and I am currently at 62kb for the `vue-google-maps.js `. I wanted to ask what is the purpose of the stubbed one? Is that suppose to have marker-clusterer and lodash omitted, like an external dependency that is not bundled with it ?

**Comment by xkjyeah** [comment]
Hey thanks for your effort.

The stubbed version is intended for SSR frameworks that do not support
importing Vue files, e.g. Nuxt.

This is because the library needs to run both on the client and on the
server side (but server side is a no op).

Server side doesn't support importing Vue files, but the webpacked version
does, and webpack has a special option to allow the style loader references
to be a no op when run on the server.

https://github.com/xkjyeah/vue-google-maps/issues/73

**Comment by dobromir-hristov** [comment]
OK so a few things i did so far.

Removed the assert library, total waste, just throw errors.

Most of the Lodash functions are not needed, like forEach and a few others. Sure its allot cleaner in some cases, but regular JavaScript loops can do the trick and we loose allot of bulk. I have not touch allot there, just saying that I could.

Added two plugins. `babel-lodash` and `lodash-webpack-plugin`.

Switched from requiring whole lodash to just the separate functions we need.

Removed the stubs config from webpack and added them as externals. They were one of the causes to load the whole lodash library, even in the separate components. I think webpack will require lodash if its inside a node env.

Moved babel from es2015 preset to env. 

Removed the transform-runtime. It adds allot of unneeded pollyfills. 

I have not tested SSR yet, but the rest works with me. I dropped from 2mb to 600kb chunks. I will see what else I can do.

Please if someone else has some time, can they try my fork?

**Comment by xkjyeah** [comment]
Hi I've picked the changes and merged them in.

Does it help reduce your build size?

**Comment by eruby94** [comment]
@xkjyeah I'm currently trying to use this for a static generated site in nuxt, and the build is less than 2mb, but still seems bloated, and throws a build error as shown below:

![screen shot 2017-10-23 at 10 43 59 am](https://user-images.githubusercontent.com/12565404/31895421-20afc4ae-b7df-11e7-8127-feea99f28a9d.png)

For now I'm going to fork it and try to remove the unused components, all I am using is map and marker.

**Comment by xkjyeah** [comment]
For nuxt, can you see the solution posted in #206 works for you?

**Comment by eruby94** [comment]
Allow me to clarify:

The package works fine when I use it as a plugin, but the plugin code makes my build way too large (>1.5mb). This could be alright for plain SSR, but for a static site, the build does not allow for such large file sizes. Also, the error above is due to something uglify does not like.

The package is super easy to use, but I couldn't get it to work properly with the `nuxt generate` command, due to the above mentioned error.

Also in general, when you're building for the web, anything ~1mb or above is somewhat ludicrous for mobile page loading.

**Comment by xkjyeah** [comment]
The error occurs because Uglify couldn't parse ES6 syntax. And so it was
not able to minify the JavaScript.

Fix the ES6 parse error, and you should get a smaller build size.

**Comment by eruby94** [comment]
I can't tell what the parse error is (maybe I'm missing something obvious)

**Comment by eruby94** [comment]
The code doesn't look weird to me, but I can take another look

**Comment by xkjyeah** [comment]
Lodash has been removed as a plugin. However will now be dependencies on babel-runtime.
