### ISSUE TITLE
$mapObject of undefined when implementing bounds

### ISSUE THREAD

**Issue by craigward** [xkjyeah/vue-google-maps#172]
I'm having issues implementing a map that always shows the markers I have. The center of the map is defined by the user (the location they are searching from) and the markers are locations near them.

@xkjyeah kindly sent me an [example](http://xkjyeah.github.io/vue-google-maps/latLngBounds.html) and I have implemented a watch 

```
watch: {
    markers(markers) {
      const bounds = new google.maps.LatLngBounds()
      for (let m of markers) {
        bounds.extend(m.position)
      }
      this.$refs.map.$mapObject.fitBounds(bounds)
    }
  },
```

However, I get a `Cannot read property '$mapObject' of undefined` error. I have read a [similar issue](https://github.com/xkjyeah/vue-google-maps/issues/48) but I still get the same issue.

Am I missing something? The below is my map

```
<gmap-map refs="gmap" class="map" v-if="!dataLoading"
        :center="{lat:$store.state.latitude, lng:$store.state.longitude}"
        :zoom="1"
        :options="options"
        :scrollwheel="false"
        map-type-id="terrain"
      >
        <gmap-marker
          :key="index"
          v-for="(m, index) in markers"
          :position="m.position"
          :clickable="true"
          :draggable="false"
          @click="locationData = m.data"
        ></gmap-marker>
</gmap-map>
```

**Comment by xkjyeah** [comment]
ref not refs

On 28 Jul 2017 5:48 pm, "Craig Ward" <notifications@github.com> wrote:

I'm having issues implementing a map that always shows the markers I have.
The center of the map is defined by the user (the location they are
searching from) and the markers are locations near them.

@xkjyeah <https://github.com/xkjyeah> kindly sent me an example
<http://xkjyeah.github.io/vue-google-maps/latLngBounds.html> and I have
implemented a watch

watch: {
    markers(markers) {
      const bounds = new google.maps.LatLngBounds()
      for (let m of markers) {
        bounds.extend(m.position)
      }
      this.$refs.map.$mapObject.fitBounds(bounds)
    }
  },

However, I get a Cannot read property '$mapObject' of undefined error. I
have read a similar issue
<https://github.com/xkjyeah/vue-google-maps/issues/48> but I still get the
same issue.

Am I missing something? The below is my map

<gmap-map refs="gmap" class="map" v-if="!dataLoading"
        :center="{lat:$store.state.latitude, lng:$store.state.longitude}"
        :zoom="1"
        :options="options"
        :scrollwheel="false"
        map-type-id="terrain"
      >
        <gmap-marker
          :key="index"
          v-for="(m, index) in markers"
          :position="m.position"
          :clickable="true"
          :draggable="false"
          @click="locationData = m.data"
        ></gmap-marker>
</gmap-map>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/xkjyeah/vue-google-maps/issues/172>, or mute the thread

**Comment by craigward** [comment]
Thanks for the quick response, but changing it to ref doesn't change anything

**Comment by xkjyeah** [comment]
Ooops. I guess I should be more specific.

This part:

<gmap-map ref="HelloWorld" class="map" v-if="!dataLoading"


And then match it on the JavaScript side with:


this.$refs.HelloWorld

**Comment by craigward** [comment]
Still getting the same issue even when changed

```
<gmap-map ref="gmap" class="map" v-if="!dataLoading"

watch: {
    markers(markers) {
      const bounds = new google.maps.LatLngBounds()
      for (let m of markers) {
        bounds.extend(m.position)
      }
      this.$refs.gmap.$mapObject.fitBounds(bounds)
    }
  },
```

**Comment by xkjyeah** [comment]
Well the gmapMap won't be there if your data is still loading, because you
v-ifed it away. Maybe you should watch dataLoading

**Comment by craigward** [comment]
OK, I removed the v-if and I don't get the error anymore, but it's also not resizing the map to fit the markers on. I'll start working on that now.

Thanks for all the help @xkjyeah
