### ISSUE TITLE
Maps not rendering

### ISSUE THREAD

**Issue by CrixuAMG** [xkjyeah/vue-google-maps#177]
I see a grey div with the google logo and terms of use link, but the map is not rendering.
There are no console errors as well.
The marker I've set is correctly rendering, and can be moved.
When trying to use the demo code with autocomplete I can also see that the map still fails to render, and autocomplete does nothing.
What is happening and how can I fix this?
`<div class="map">

                            <gmap-map
                                    :center="center"
                                    :zoom="7"
                                    style="margin-top: 25px; width: 100%; height: 300px"
                                    ref="map"
                                    map-type-id="terrain"
                            >

                                <gmap-marker
                                        :position="center"
                                        :clickable="true"
                                        :draggable="true"
                                        @dragend="updateMarker($event)"
                                ></gmap-marker>

                            </gmap-map>

                        </div>`

**Comment by xkjyeah** [comment]
1. Screenshot please
2. Show us *all* your code, including the JavaScript, not just the template.

On 31 Jul 2017 11:22 pm, "CrixuAMG" <notifications@github.com> wrote:

I see a grey div with the google logo and terms of use link, but the map is
not rendering.
There are no console errors as well.
The marker I've set is correctly rendering, and can be moved.
When trying to use the demo code with autocomplete I can also see that the
map still fails to render, and autocomplete does nothing.
What is happening and how can I fix this?
<div class="map"> <gmap-map :center="center" :zoom="7" style="margin-top:
25px; width: 100%; height: 300px" ref="map" map-type-id="terrain" >
<gmap-marker :position="center" :clickable="true" :draggable="true"
@dragend="updateMarker($event)" ></gmap-marker> </gmap-map> </div>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/xkjyeah/vue-google-maps/issues/177>, or mute the thread

**Comment by CrixuAMG** [comment]
Code in template: 
`<divv class="map">
                            <gmap-map
                                    :center="center"
                                    :zoom="7"
                                    style="margin-top: 25px; width: 100%; height: 300px"
                                    ref="map"
                                    map-type-id="terrain"
                            ></gmap-map>
</divv>`
(divv is not a typo (did it to fix github filtering html code))

In the script tag (hardcoded floats for testing) `computed: {
            center() {
                return new google.maps.LatLng(parseFloat(52.347824), parseFloat(5.740563));
            },
        },`

Screenshot: http://imgur.com/a/hIEDX

**Comment by CrixuAMG** [comment]
Update: just tried putting the example code in a template and it works. The code I was originally using was located inside a bootstrap-vue modal.
There are no console errors.
Any known solution for this or will I have to redesign the page?

**Comment by xkjyeah** [comment]
Call :

Vue.$gmapDefaultResizeBus.$emit('resize')

After the modal has been displayed.

If that is not possible, use setTimeout to call it, say, 200ms after you
show your modal.

**Comment by CrixuAMG** [comment]
Thanks, that solved it.
I noticed that in the (same) modal the autocomplete feature is working incorrectly. When I type 'new" or anything else nothing shows up. When I use the up/down arrows on the keyboard it does show the names of places in the input.

**Comment by CrixuAMG** [comment]
Added `.pac-container.pac-logo {
 z-index: 999999;
}` to fix this issue.
