### ISSUE TITLE
v-model not working in gmap-autocomplete

### ISSUE THREAD

**Issue by loama** [xkjyeah/vue-google-maps#186]
Hi, I am using the value of the user input for validating the field (it is only valid if the selected address has street_number) and for that I need to set a v-model

`<gmap-autocomplete
           @place_changed="setNewJobAddress"
            v-model="newJob_address_value"
            >
  </gmap-autocomplete>`

But it just doesn´t work.

Do you know any way I can avoid that?

**Comment by loama** [comment]
It can be updated from outside but writing in the gmap input does not update the model.

**Comment by xkjyeah** [comment]
You can use the native events.

e.g. @input.native, @change.native

**Comment by xkjyeah** [comment]
v-model isn't logical because it is unclear in this case what you want to be binded two-way.

In most cases, with the Autocomplete you want to return the {lat, lng}.

However, you cannot pass in the {lat, lng}, because there isn't always a human readable representation of a {lat, lng}, or it may not be the representation you want. For example, my default go-to lat lng is 1.38, 103.8, but that could variously be (1) Singapore, (2) Central Catchment Area, or (3) somewhere around Upper Pierce Reservoir. So it is up to the user to set the textual representation (via :value) manually.

If you need a component that binds two-way on the {lat, lng}, you should write a new component that wraps around Autocomplete

**Comment by xkjyeah** [comment]
Are you validating the latlng? Or the address?

**Comment by loama** [comment]
I am validating that after the user writes the address (i.e Fifth Avenue 232 New York) that address contains street_number, because the input allows to input things like "New York City" which is a city, not an address.

But also, you can write whatever you like and then hit tab and not even select a google maps option.
So I want to have the v-model binding so that:

- if the input is empty, do not show an error message
- if the input has anything but NOT a google maps option selected, show an error saying that
- if the input has anything and a google maps option, but is not an address, show another error
-if it has address show "correct"

the v-model works from outside, if I change the model from another input or something like that it does change in the gmaps-autocomplete, but from the gmaps-autocomplete it does not go outside.

**Comment by Stalinko** [comment]
I also have the same problem. I just need the input raw string value, but there is no obvious way to bind a variable to it.

`@input.native, @change.native` - isn't perfect solution because it's not fired when you select an address from the dropdown list.

**Comment by michelleLegend** [comment]
I have the same problem with Google Maps API, v-model is not capturing the value derived from autocomplete. The best workaround I found is the old fashion way, capture the value of the input field...
 ```document.getElementById('<input-id>').value```

**Comment by xkjyeah** [comment]
You can get the input value as this.$refs['REF-OF-AUTOCOMPLETE'].$el.value

There's also the `place_changed` event.
