### ISSUE TITLE
feature request: support for Street View

### ISSUE THREAD

**Issue by andrisi** [xkjyeah/vue-google-maps#19]
Would be nice to use the same component - and perhaps the same data - to show a map and a street view of an addres. You could also merge/cooperate with https://github.com/gocanto/google-autocomplete Thanks!

**Comment by xkjyeah** [comment]
Hi, thanks for the suggestion. I've never embedded a Street View in a web page before. Do you know how it can be done? It shouldn't be hard to create a component if you can provide an example.

As for showing the map... it can be done, but through a somewhat manual process, because I would assume that people want to lay out their maps and their autocomplete in different ways.

[Example](http://crowdsource.beeline.sg/static/index.html) -- note: you will have to dig up the internals yourself as the source code isn't public.

**Comment by andrisi** [comment]
I havent embedded Street View before, but it seems to work the same way as the maps: https://developers.google.com/maps/documentation/javascript/examples/streetview-embed

**Comment by xkjyeah** [comment]
Ok. Looks doable. I'll split this issue into two issues. One for Street View and one for Autocomplete. This project inherited PlaceInput from vue-google-maps, but I agree with the direction taken by https://github.com/gocanto/google-autocomplete -- it should focus only on the autocomplete, without all the other extras (such as label, div)

**Comment by xkjyeah** [comment]
http://xkjyeah.github.io/vue-google-maps/street-view-pano.html
