### ISSUE TITLE
Map inside a modal

### ISSUE THREAD

**Issue by FrancescoMussi** [xkjyeah/vue-google-maps#210]
I have the good old js issue of a google map not displaying inside a modal..

The map is just a grey screen - and it works only after it has been "touched" by the user (manually zoom in/out etc..). In this way the map get refreshed and become displayed properly.

![screen shot 2017-09-13 at 15 36 58](https://user-images.githubusercontent.com/5312907/30377747-9762054a-9899-11e7-86c2-5ea605d1987c.png)

So the trick is to somehow to refresh it beforehand.

There are some workaround in Jquery and Angular.
For example:
https://stackoverflow.com/questions/11742839/showing-a-google-map-in-a-modal-created-with-twitter-bootstrap

Do you know in this case how can I somehow refresh the map once the modal is opened?

**Comment by xkjyeah** [comment]
Yep!

https://xkjyeah.github.io/vue-google-maps/resize-bus.html

(View source code for the answer)

**Comment by FrancescoMussi** [comment]
Thanks.
Actually the trick was to delay a bit the `Vue.$gmapDefaultResizeBus.$emit('resize');`
Without the delay the map was still blank, with 200ms of delay the map get refreshed and it is shown.
I don't guarantee it works on all cases. I am testing now on localhost. Maybe online it may be needed to increase the delay a little bit.
This is my code:

`<a href="#" class="btn btn-success" @click="initMapModal($event)"><i class="fa fa-map-marker" aria-hidden="true" data-toggle="modal" data-target="#mapModal"></i></a>`

```
<div class="modal fade" id="mapModal" tabindex="-1" role="dialog" aria-labelledby="mapModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="mapModal">
          Location
        </h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">
            &times;
          </span>
        </button>
      </div>
      <div class="modal-body">
       <gmap-map
          class="locationMap"
          :center="{lat:10, lng:10}"
          :zoom="1"
        ></gmap-map>
      </div>
    </div>
  </div>
</div>

```

```
<style>
  .locationMap {
    height: 300px;
  }
</style>
```
```

methods: {
initMapModal(event){
  event.preventDefault();
  setTimeout(this.mapResize, 200);
},

mapResize(){
  Vue.$gmapDefaultResizeBus.$emit('resize');
},

}
```

**Comment by xkjyeah** [comment]
Are you using bootstrap to display the modal? If so, you could try adding
the resize trigger to the shown.bs.modal modal event

On 14 Sep 2017 4:36 pm, "Francesco Mussi" <notifications@github.com> wrote:

Thanks.
Actually the trick was to delay a bit the Vue.$gmapDefaultResizeBus.$
emit('resize');
Without the delay the map was still blank, with 200ms of delay the map get
refreshed and it is shown.
I don't guarantee it works on all cases. I am testing now on localhost.
Maybe online it may be needed to increase the delay a little bit.
This is my code:

<a href="#" class="btn btn-success" @click="initMapModal($event)"><i
class="fa fa-map-marker" aria-hidden="true" data-toggle="modal"
data-target="#mapModal"></i></a>

<div class="modal fade" id="mapModal" tabindex="-1" role="dialog"
aria-labelledby="mapModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="mapModal">
          Location
        </h5>
        <button type="button" class="close" data-dismiss="modal"
aria-label="Close">
          <span aria-hidden="true">
            &times;
          </span>
        </button>
      </div>
      <div class="modal-body">
       <gmap-map
          class="locationMap"
          :center="{lat:10, lng:10}"
          :zoom="1"
        ></gmap-map>
      </div>
    </div>
  </div>
</div>


<style>
  .locationMap {
    height: 300px;
  }
</style>


methods: {
initMapModal(event){
  event.preventDefault();
  setTimeout(this.mapResize, 200);
},

mapResize(){
  Vue.$gmapDefaultResizeBus.$emit('resize');
},

}

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/xkjyeah/vue-google-maps/issues/210#issuecomment-329413762>,
or mute the thread

**Comment by FrancescoMussi** [comment]
Yes I am using bootstrap. But the regular one. Not [vue-bootstrap](https://bootstrap-vue.js.org/). 
I may actually consider using vue-bootstrap.
Otherwise do you know how to trigger `shown.bs.modal `with Vue?

**Comment by xkjyeah** [comment]
Sorry, not to trigger it. I meant to say, add an event handler where you
listen for the shown.bs.modal event, and in the event handler tell the
resize bus to resize.

On 14 Sep 2017 4:59 pm, "Francesco Mussi" <notifications@github.com> wrote:

Yes I am using bootstrap. But the regular one. Not vue-bootstrap
<https://bootstrap-vue.js.org/>.
I may actually consider using vue-bootstrap.
Otherwise do you know how to trigger shown.bs.modalwith Vue?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/xkjyeah/vue-google-maps/issues/210#issuecomment-329419268>,
or mute the thread

**Comment by FrancescoMussi** [comment]
Okay thanks. I will try also vue-bootstrap and see how it behave.

**Comment by FrancescoMussi** [comment]
I have tried the [modal component of vue-bootstrap](https://bootstrap-vue.js.org/docs/components/modal). I refresh the map on the `shown` event.

In this way the map get refreshed once the modal is shown and it is properly displayed.

This is the code:

```
<b-modal ref="mapModal" @shown="refreshMap">

  <gmap-map class="locationMap" :zoom="zoomLevel" :center="mapCenter">
     <GmapMarker v-for="(marker, index) in markers"
      :key="index"
      :position="marker.position"
      />
   </gmap-map>

</b-modal>

```

```
refreshMap(){

  Vue.$gmapDefaultResizeBus.$emit('resize');
}
```

So we can close the issue :)
Thanks for the help!
Awesome component!
