### ISSUE TITLE
Custom marker icon

### ISSUE THREAD

**Issue by EddyTheDove** [xkjyeah/vue-google-maps#215]
Hi, thanks for your library. 
I'm trying to customise my markers with a custom icon. Your API states the marker icon should be an object but does not give those icon properties. In google maps, for instance, the icon is just a string.

Can someone tell me what the icon properties are?
Thank you very much.

**Comment by xkjyeah** [comment]
Hi,

The properties you pass into :icon are passed straight into the Google Maps JS API. This library has been designed to follow the official API as closely as possible, so that you can transfer whatever you know about the Google API to here. 

Sorry for the mistake in the API docs. Just go ahead and pass in a string. It should work.
