### ISSUE TITLE
0.8.3 SSR uglifyJs bug

### ISSUE THREAD

**Issue by xrei** [xkjyeah/vue-google-maps#217]
I've updated plugin to latest version, fixed import with main/src and in dev mode all fine.
But when i try to compile to production, i'm seeing this error 
![image](https://user-images.githubusercontent.com/9521710/30776540-d8fb1716-a0b0-11e7-86cf-d6a1989c2de2.png)

My uglifyJs config: 
```
    new webpack.optimize.UglifyJsPlugin({
      compress: { warnings: false }
    }),
```
So i reverted back to 0.7.10 version and i don't see this error. 

I made empty vue cli webpack template and it also doesn't work with this import
import * as VueGoogleMaps from '../node_modules/vue2-google-maps/src/main'
![image](https://user-images.githubusercontent.com/9521710/30776641-ca6a9634-a0b2-11e7-8082-9fc9b7f9faf0.png)

Any thoughts what's wrong? Thx.

**Comment by xkjyeah** [comment]
Your webpack Babel-loader needs to be set up to  process
node_modules/vue2-google-maps too. That's my guess

On 24 Sep 2017 3:59 am, "Roman" <notifications@github.com> wrote:

I've updated plugin to latest version, fixed import with main/src and in
dev mode all fine.
But when i try to compile to production, i'm seeing this error
[image: image]
<https://user-images.githubusercontent.com/9521710/30776540-d8fb1716-a0b0-11e7-86cf-d6a1989c2de2.png>

My uglifyJs config:

    new webpack.optimize.UglifyJsPlugin({
      compress: { warnings: false }
    }),

So i reverted back to 0.7.10 version and i don't see this error.

I made empty vue cli webpack template and it also doesn't work with this
import
import * as VueGoogleMaps from '../node_modules/vue2-google-maps/src/main'
[image: image]
<https://user-images.githubusercontent.com/9521710/30776641-ca6a9634-a0b2-11e7-8082-9fc9b7f9faf0.png>

Any thoughts what's wrong? Thx.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/xkjyeah/vue-google-maps/issues/217>, or mute the thread

**Comment by christophemarois** [comment]
Same here!

**Comment by suhogrozdje** [comment]
@xkjyeah Can you provide an example of how to do that, please?

**Comment by xkjyeah** [comment]
Put a rule in your webpack config:

```js
module: {
   rules: [
       ...
       {
            loader: 'babel-loader',
            include: [ path.resolve(__dirname, 'node_modules/vue2-google-maps/src') ]
       }
    ]
}
```

**Comment by christophemarois** [comment]
After trying hours with the latest Nuxt.js RC version, I downgraded to `0.7.10` to get rid of the UglifyJsPlugin error

**Comment by janhox** [comment]
@christophemarois,
is there anything else you had to do to make this build ? 
I receive the below error when building, have bumped to 0.7.10 ?
I am using Nuxt version 1.0.0-rc6.
Thanks.

<img width="910" alt="screen shot 2017-09-30 at 17 40 45" src="https://user-images.githubusercontent.com/24571106/31047213-ade10170-a606-11e7-9afc-ae031ced33b4.png">

**Comment by xrei** [comment]
So i found the solution.
Install **uglifyjs-webpack-plugin**
`npm i -D uglifyjs-webpack-plugin@beta`
It is important to install beta version.

And then in your base webpack config add these lines:
```
const uglify = require('uglifyjs-webpack-plugin')

module.exports = {
  // your webpack other settings
  plugins: [
    new uglify()
    // other plugins that you might have
  ]
}
```

**Comment by christophemarois** [comment]
@janhox no, no extra steps. I'm on Nuxt `1.0.0-rc9` and vue2-google-maps `0.7.10`. I use it like this:

```javascript
import Vue from 'vue'
import * as VueGoogleMaps from '~/node_modules/vue2-google-maps'

Vue.use(VueGoogleMaps, {
  load: {
    key: [...]
  }
})
```

**Comment by janhox** [comment]
@christophemarois, thanks that works for me as well. It was the import that needed changing.
@romanrei, will try your suggestion as well so I can keep latest version.

**Comment by SyedAman** [comment]
@janhox @christophemarois how did you guys downgrade? I just tried changing the `nuxt` version in my `package.json`.

Does downgrading require re-installing the nuxt template?

**Comment by islamhaqq** [comment]
confirmed downgrading `vue-google-maps` to `v0.7.10` works thanks to @christophemarois. 

But be sure to change your import to 

`import * as VueGoogleMaps from '~/node_modules/vue2-google-maps'` instead of `import * as VueGoogleMaps from '~/node_modules/vue2-google-maps/src/main'` since `src/main` was added in `0.8`.

**Comment by Darkside73** [comment]
```v0.7.10``` works for me with nuxt ```1.0.0-rc11```

**Comment by xkjyeah** [comment]
Nuxt users, try the solution at https://github.com/xkjyeah/vue-google-maps/issues/206#issuecomment-338689932

**Comment by diegoazh** [comment]
It is considered fixed.
