### ISSUE TITLE
Bounds and Zoom are not reactive

### ISSUE THREAD

**Issue by Sevavietl** [xkjyeah/vue-google-maps#25]
Thanks for the vue2 support.

When I use the basic example from readme I face several issues:

1. Bounds don't set when initialized (in vue dev-tools they are undefined). As I understand, if I set center and zoom, bounds should be calculated automatically. How can I achieve this?

2. When I change map zoom it is not changed if I look in the vue dev-tools. Is this expected behavior?

Thank you in advance.

**Comment by xkjyeah** [comment]
Yes, it is expected behaviour. 2-way binding is no longer supported in Vue 2.x.

You can get the current zoom/bounds by adding a zoom_changed and bounds_changed listener. e.g.

```html
<gmap-map @zoom_changed="zoom = $event" :zoom="zoom" @bounds_changed="bounds = $event"></gmap-map>
```

However you *must* not do the same for `center` because google maps does not guarantee that the map center is exactly the center you requested, i.e.
```js
map.$mapObject.setCenter(c)
var d = map.$mapObject.getCenter()
assert.equal(c.lat, d.lat()) // Assertion fails in the general case
```

If you do so, you *will* end up with an infinite set/get loop.

**Comment by Sevavietl** [comment]
Thank you for the quick response and explanation.

Can you advise me how can I set up bounds initially? I understand how to update bounds when they are changed. But cannot figure out how to force the map to set bounds after initialization. I mean computed bounds, not user provided.

Thank you in advance.

**Comment by xkjyeah** [comment]
Unfortunately you'll have to do it programmatically. The Google maps API
does not expose a setBounds, and I think for a good reason; but it exposes
fitBounds. So if you set up a ref to a gmap-map, you can write:

```js
this.$refs.map.fitBounds(bounds)
```

**Comment by Sevavietl** [comment]
Thank you.
