### ISSUE TITLE
Get the value of the props in GMap Circle

### ISSUE THREAD

**Issue by rannieo** [xkjyeah/vue-google-maps#320]
Hi guys,

How can i get the value of GMAP Circle?
This is the snippet,
`        <gmap-circle v-for="(municipality, index) in municipalities"
                    :key="municipality.coord.lat"
                    :center="municipality.coord"
                      :clickable="true"
                      @click="showInfo"
                      :ref="municipality.name">
        </gmap-circle>`

The scenario will be, when i click the circle, it gets the `center` props, 

![sa](https://user-images.githubusercontent.com/23412411/36069828-6d395eb8-0f2b-11e8-8029-c039079a2c74.PNG)

**Comment by xkjyeah** [comment]
Is this an editable circle? Typically you pass the value from the parent to the child

**Comment by rannieo** [comment]
Yes, i've pass the data from parent to child.

**Comment by rannieo** [comment]
The event will be, if i click the circle ill get the value of the props..

**Comment by xkjyeah** [comment]
Show everyone how you are currently defining your circle please?

**Comment by rannieo** [comment]
This is the snippet,
`        <gmap-circle v-for="(municipality, index) in municipalities"
                    :key="municipality.coord.lat"
                    :center="municipality.coord"
                      :clickable="true"
                      @click="showInfo"
                      :ref="municipality.name">
        </gmap-circle>`

The scenario will be, when i click the circle, it gets the `center` props value,

**Comment by xkjyeah** [comment]
@click="showInfo(municipality.coord)"

On 11 Feb 2018 17:28, "rannieollit" <notifications@github.com> wrote:

This is the snippet,
<gmap-circle v-for="(municipality, index) in municipalities"
:key="municipality.coord.lat" :center="municipality.coord"
:clickable="true" @click="showInfo" :ref="municipality.name"> </gmap-circle>

The scenario will be, when i click the circle, it gets the center props,

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/xkjyeah/vue-google-maps/issues/320#issuecomment-364736879>,
or mute the thread

**Comment by rannieo** [comment]
Thanks, i forgot to pass the variable in the method!

`  methods: {
    showInfo(coord) {
      this.$refs.modal.open()
      console.log(coord);
    }
  },`
