### ISSUE TITLE
Problems with reactive properties

### ISSUE THREAD

**Issue by Dylan-Chapman** [xkjyeah/vue-google-maps#327]
I don't know if I'm doing something wrong, but I'm having a few issues/questions.

Whenever I pan the map, the ```this.$refs.map.bounds``` is undefined. Is there a way for me to ```watch``` the map bounds for change, so I can react to it?

Additionally, whenever I try using the ```MapElementMixin```, ```this.$map.getBounds()``` reports only the initial bounds, even when panning the map around and calling it again, it reports the same bounds. 

Is there a way to watch properties like this (bounds, center, zoom)? I'm not trying to set anything. I just want to watch them so I can do other things in my app.

**Comment by xkjyeah** [comment]
The map class has the `bounds_changed`, `zoom_changed` and `center_changed` properties, so you could do something like:
```vue
<GmapMap @bounds_changed=... @zoom_changed=... @center_changed=... />
```

If you want to do it from the descendent element, you'll have to bind the listeners manually, i.e.
```js
google.maps.event.addListener(this.$map, 'bounds_changed', handler)
```

If `getBounds()` is returning only the initial bounds, then it's a Google Maps API problem (i.e. unlikely). Therefore -- check your code again? Maybe you should define a function instead?

**Comment by Dylan-Chapman** [comment]
Okay, I'll double check and see if there's a problem with my ```getBounds()``` call and use an event listener otherwise. Out of curiosity, is there a technical reason for these properties not being reactive on the map instance, though? It would be a useful feature to have in my opinion and would make the need for event listeners less common.

**Comment by xkjyeah** [comment]
https://vuejs.org/v2/guide/components.html#One-Way-Data-Flow

On 18 Feb 2018 00:26, "Dylan Chapman" <notifications@github.com> wrote:

Okay, I'll double check and see if there's a problem with my getBounds()
call and use an event listener otherwise. Out of curiosity, is there a
technical reason for these properties not being reactive on the map
instance, though? It would be a useful feature to have in my opinion and
would make the need for event listeners less common.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/xkjyeah/vue-google-maps/issues/327#issuecomment-366452471>,
or mute the thread

**Comment by Dylan-Chapman** [comment]
Hm, I guess it's over my head how that violates the one way data flow with the properties reflecting their current state. Regardless, I've got this working by going in a bit different of a direction now. Thanks!
