### ISSUE TITLE
Map Moves Randomly When Clicking A Marker in v0.8.6

### ISSUE THREAD

**Issue by snow-drop** [xkjyeah/vue-google-maps#331]
Good day. I am currently using vue-google-maps and today, after deleting my old node_modules and installing again the latest ones (currently v0.8.6), map moves randomly around the markers everytime I click on any marker when displaying an info window. Downgrading v.0.8.4 fixes the issue. I have not check if it can be replicated in v.0.8.5.

Update: When all markers are visible on the map, map moves a little but when you zoom it so that some markers are not visible, it moves randomly on different markers.

**Comment by xkjyeah** [comment]
Darn. Do you have a test case that I can debug on?

**Comment by snow-drop** [comment]
I've updated my comment above. You mean some sample code to replicate the issue?

**Comment by xkjyeah** [comment]
Yes please

On 21 Feb 2018 10:58, "snow-drop" <notifications@github.com> wrote:

I've updated my comment above. You mean some sample code to replicate the
issue?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/xkjyeah/vue-google-maps/issues/331#issuecomment-367198062>,
or mute the thread

**Comment by snow-drop** [comment]
Sure, thanks. I am not able to do it now though for some reasons. I'm going to reply here after a few hours for the code to replicate the issue.

**Comment by snow-drop** [comment]
Try this code here:
```
<gmap-map
    :center="{lat: 50 + Math.random(), lng: 90 + Math.random()}"
    :zoom="7"
    :style="'height: 300px;'"
    ref="map">

    <gmap-marker
        v-for="(position, index) in positions"
        :key="index"
        :position="position"
        :clickable="true"
        @click="openInfoWindowTemplate(positions[index])"
        ref="markers">
    </gmap-marker>

    <gmap-info-window
        :options="{maxWidth: 300}"
        :position="infoWindow.position"
        :opened="infoWindow.open"
        @closeclick="infoWindow.open=false">
        <div v-html="infoWindow.template"></div>
    </gmap-info-window>
</gmap-map>

    <gmap-info-window
    :options="{maxWidth: 300}"
    :position="infoWindow.position"
    :opened="infoWindow.open"
    @closeclick="infoWindow.open=false">
    <div v-html="infoWindow.template"></div>
    </gmap-info-window>
</gmap-map>

....

data () {
    return {
        infoWindow: {
            position: {lat: 0, lng: 0},
            open: false,
            template: ''
        }
    }
},
computed: {
     positions () {
        let list = []
        for (let i = 0; i < 100; i++) {
            list.push({lat: 50 + Math.random(), lng: 90 + Math.random()})
        }
        return list
    }
}
```

**Comment by xkjyeah** [comment]
v0.8.6 checked for changes in the latlng in a different way compared to v0.8.4.

Somehow this seems to trigger a re-render of the entire map component, which resulted in `Math.random()` being run a second time. The problem is, if you put a raw expression into the virtual DOM, there are no guarantees about how often it executes.

If you need to guarantee that the expression `:center="{lat: 50 + Math.random(), lng: 90 + Math.random()}"` is computed exactly once, you should put it in a computed value, like so:
1. https://github.com/xkjyeah/vue-google-maps/blob/vue2/test/test-pages/test-marker-with-infowindow.html#L8
2. https://github.com/xkjyeah/vue-google-maps/blob/vue2/test/test-pages/test-marker-with-infowindow.html#L56

**Comment by snow-drop** [comment]
@xkjyeah The issue occurs also when using computed value though. Can you replicate this? Just to make sure if the problem is on my local setup or not.

**Comment by xkjyeah** [comment]
I couldn't replicate the problem after I switched to the computed value. Could you dump your code here again?

**Comment by snow-drop** [comment]
I can't do it for the mean time so I'll update it here later. Thanks!

**Comment by snow-drop** [comment]
@xkjyeah Seems it is already working on v0.8.8. Thanks!
