### ISSUE TITLE
Problem with Vue.js 2.1.8

### ISSUE THREAD

**Issue by lukaszflorczak** [xkjyeah/vue-google-maps#34]
Hi!

I just tried to use the plugin with Vue.js v. 2.1.8, but it doesn't work :(

I get an error:

`createElm — vue.js:4062
TypeError: undefined is not an object (evaluating 'vnode.isRootInsert = !nested')`

**Comment by xkjyeah** [comment]
Hi can you give me more details?

On 18 Jan 2017 04:48, "Lukasz Florczak" <notifications@github.com> wrote:

Hi!

I just tried to use the plugin with Vue.js v. 2.1.8, but it doesn't work :(

I get an error:

createElm — vue.js:4062TypeError: undefined is not an object (evaluating
'vnode.isRootInsert = !nested')

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/xkjyeah/vue-google-maps/issues/34>, or mute the thread

**Comment by lukaszflorczak** [comment]
I just try to init a map by the plugin:

```
<div id="map" class="map">
    <gmap-map style="width: 100%; height: 100%; position: absolute; left:0; top:0"
	:center="{lat: 1.38, lng: 103.8}"
	:zoom="12"
    ></gmap-map>
</div>
```

```
Vue.use(VueGoogleMap, {
    load: {
        key: APIKEY,
    }
});

new Vue({
    el: '#map',
});
```

When I tried to use it with latest Vue.js version, map was not loaded and I had an error in a browser console: 
```createElm — vue.js:4062 TypeError: undefined is not an object (evaluating 'vnode.isRootInsert = !nested')```

But when I changed Vue.js for 2.1.6 it works fine.

**Comment by xkjyeah** [comment]
Where did you get your copy of vue-google-maps.js from? This seems like a
compilation issue. After I update the source you should be able to use Vue
2.1.8.

**Comment by xkjyeah** [comment]
Hi, please try with the latest version of vue-google-maps.js in the Git repo. It should be compatible with Vue 2.1.10 (latest version).

**Comment by lukaszflorczak** [comment]
Thank you! Everything works fine now.
