### ISSUE TITLE
Q: Non transpiled vue files

### ISSUE THREAD

**Issue by Ornhoj** [xkjyeah/vue-google-maps#357]
Is there a reason for not compiling the vue files in `dist/components`?

**Comment by xkjyeah** [comment]
At the moment, I am not aware of any library that transpiles .vue files
directly to a plain JS file. It is possible with JSX because JSX is
Javascript with syntactic sugar. However, vue files come attached with
other assumptions like CSS.

The only known transpiler (that I know of) for .vue files is vue-loader,
and that is a webpack plugin, and it's only output is a webpack bundle. The
bundle will then come with other add-ons like a Babel runtime / polyfill
and Webpack boilerplates. To minimize this overhead, I chose to distribute
this library as .vue files.

This was also the recommendation by Evan You (
https://webcache.googleusercontent.com/search?q=cache:KIdExP_9JDcJ:https://forum-archive.vuejs.org/topic/1203/how-to-bundle-a-set-of-vue-components-efficiently/3+&cd=1&hl=en&ct=clnk&gl=uk&client=firefox-b-ab)
in response to Guillaume Leclerc (the original author of this library).

At that time, he chose to export the entire bundle, but it caused problems
with server-side rendering (IIRC, CSS), so I've decided to just distribute
.vue files.

**Comment by Ornhoj** [comment]
Thank you for your feedback.
Unfortunately the link is broken - so I couldn't read your reference - however I did find this link: https://github.com/nuxt/nuxt.js/issues/1202

And my initial reason for asking my question is that I get the 
`Unexpected token <` error you are getting when I server side render the `vue2-google-maps` package as it is now.

Did you find a way to circumvent this issue? - Or is maintaining vue files your solution?

Cheers

**Comment by xkjyeah** [comment]
Please see the Wiki for a possible solution

**Comment by Ornhoj** [comment]
Your wiki helped after my sleepdeprived brain understod I had to create an alias for my root to use `~`.

I added my experience to the Wiki page (I hope you don't mind):
https://github.com/xkjyeah/vue-google-maps/wiki/Developing---Building---Nuxt---ESLint-FAQ

**Comment by xkjyeah** [comment]
Oh dear, is it not part of the default Nuxt configuration?

**Comment by Ornhoj** [comment]
It is, but I come from a custom webpack build (non-nuxt.js) and did not notice the `~` was an alias.
