### ISSUE TITLE
GMapAutoComplete V-model

### ISSUE THREAD

**Issue by evanRoberto** [xkjyeah/vue-google-maps#408]
How to use v-model on gmapautocomplete

**Comment by MonserratGenereux** [comment]
I have the same cuestion 🤔

**Comment by runxc1** [comment]
It does not seem possible.  It would be nice to have a way to do two way binding.  currently I have to read the Dom.

**Comment by xkjyeah** [comment]
The curious question is, what are you trying to bind to? Are you binding to the `Place` object, the string description, the lat-lng or? If you bind to a `Place` object, how do you create one for a location you read from your database?

Because different use cases have different needs (some need a lat-lng, others need an address, ...) no particular implementation is provided.

**Comment by myonetop** [comment]
<gmap-autocomplete  @place_changed="setPlace" @input="autocompleteUser($event, search, index)" v-on:keydown.enter.prevent="onBlurSearchInput"></gmap-autocomplete>

// method

    async autocompleteUser(e, value, index) {
      if (e.constructor.name !== 'InputEvent') {
        this.usersAutocomplete = []
        return
      }
      let that = this
      await axios.get()//fetching data
        .then(response => {
          that.usersAutocomplete = response.data
        })
    },
if you get issue  "ReferenceError: axios is not defined", run npm install --save axios
