### ISSUE TITLE
Dynamic language/region binding

### ISSUE THREAD

**Issue by aslak01** [xkjyeah/vue-google-maps#63]
Is it possible to make the load parameters respond to vue variables in my component? Or send them from another level of my code than the one specified in the documentation? 

```
Vue.use(VueGoogleMaps, {
load: {
	key: 'xxx',
	language: 'DYNAMIC?',
	region: 'DYNAMIC?'
	}
});
```

**Comment by xkjyeah** [comment]
Yes that is possible, but it can only happen once when your page is loaded.
This is a limitation of the Google Maps API

On 7 Mar 2017 10:38 p.m., "aslak01" <notifications@github.com> wrote:

Is it possible to make the load parameters respond to vue variables in my
component? Or send them from another level of my code than the one
specified in the documentation?

Vue.use(VueGoogleMaps, {
load: {
	key: 'xxx',
	language: 'DYNAMIC?',
	region: 'DYNAMIC?'
	}
});

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/xkjyeah/vue-google-maps/issues/63>, or mute the thread

**Comment by aslak01** [comment]
In that case it doesn't make sense to implement it in my application for the limited benefit it provides. I guess the best thing is to leave it without an explicit region definition so the users' local regionalisations apply. 

I have another question tho: Is there a way to integrate Gmap Directions dynamically? I'd like to bind some buttons to highlight the road and water routes to get here.

**Comment by xkjyeah** [comment]
yes it is possible. just use google.maps.DirectionsService

**Comment by aslak01** [comment]
Do you think you could give me a hint about how to achieve this? I'm not too familiar with the google maps api, and it doesn't seem to show up in the docs.

**Comment by havgry** [comment]
Could you possibly elaborate on the localization issue, @xkjyeah? In my opinion it's an essential thing and it's pretty trivial to implement with the regular Google Maps API.
