### ISSUE TITLE
Confused about project roadmap, forks and future steps

### ISSUE THREAD

**Issue by XaviTorello** [xkjyeah/vue-google-maps#719]
Hi folks! Thanks for this great project, I know that it involves a lot of time and energy :) 🍻

I have some doubts about the current situation. I can't understand why there are 3 different forks for the same package ... It's strange and introduces more volatility to the JS ecosystem.

@diegoazh, will not be better to submit new PRs to this repo? Join forces into the same project seems to be the best strategy from my perspective. Or this current repo is dead?

Just to clarify it, this repo will be archived @xkjyeah? Should we move to @diegoazh project as a new maintainer, or both will live in parallel?

If it, please, review the details of both projects. Both descriptions point to the same npm package (see https://www.npmjs.com/package/gmap-vue#with-npm-recommended):
`` ''
With npm (Recommended)
npm install vue2-google-maps
`` ''

Also a simple roadmap for both projects will contribute to understand the current scenario and new routes.

Please, shed some light :)

**Comment by diegoazh** [comment]
Hi @XaviTorello, the current state of this project is stopped when we talk about releases, the owner of `vue-google-maps2` said in [other thread](https://github.com/xkjyeah/vue-google-maps/issues/514#issuecomment-606638192) that he hasn't time to review all features added to this package and land a new version, he encourages the community to fork the project and continues the development of this package from there, is because of this that I fork the project.
About your question over different forks, is a consequence of other contributors land your own packages because a new release was delayed. On the other hand, the confusion about the description, that you mention, is because I land a new version of this package in order to give the community all new features added to this repository and I forgot to modify the description correctly in the readme file.
The PRs in this project are welcome, I don't know if this repository will land a new version in a near feature, but it will be reviewed and merged if they are fine. The only thing that I can ensure you is that in `gmap-vue` package we will plane develop and land new versions when new features are added to it.
I hope that I have clarified your doubts.
Regards.

**Comment by XaviTorello** [comment]
Many thanks @diegoazh, I'll move to `gmap-vue` ASAP.

@xkjyeah, maybe to archive this repository will be a good idea to quickly identify that the development is not continued anymore (also deleting the "CONTRIBUTORS NEEDED" section at the top of README) :)

Thanks for your time and efforts folks!
