### ISSUE TITLE
Autocomplete: catch events from input element

### ISSUE THREAD

**Issue by karudo** [xkjyeah/vue-google-maps#84]
How i can catch event (e.g. focus) from autocomplete input element? 
If i do `<gmap-autocomplete @focus="onfocus"` it  does not work.

**Comment by xkjyeah** [comment]
@focus.native

On 3 Apr 2017 18:39, "Deonis Peretyagin" <notifications@github.com> wrote:

How i can catch event (e.g. focus) from autocomplete input element?
If i do <gmap-autocomplete @focus="onfocus" it does not work.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/xkjyeah/vue-google-maps/issues/84>, or mute the thread
