### ISSUE TITLE
lodash is fully imported doubling the size

### ISSUE THREAD

**Issue by maxim25** [xkjyeah/vue-google-maps#89]
When compiling my app I noticed that lodash doubles the size of this library. Any chance we can refactor a little and only include the functions that are needed? Or maybe utilizing the lodash-webpack-plugin?

**Comment by xkjyeah** [comment]
Hi,

Do you think you can play around with the webpack config and see if you can
fix the issue? And then submit a PR?

**Comment by kosmos** [comment]
Maybe this plugin will help: 
https://github.com/lodash/babel-plugin-lodash

**Comment by magicspon** [comment]
I've made a fork and replaced the lodash imports with smaller lodash.modules
However, I'm getting a world of webpack errors when I try and compile the example build

https://github.com/magicspon/vue-google-maps

**Comment by maxim25** [comment]
@magicspon I had the same issue when I tried adding webpack lodash plugins. Not sure what's going on as I am no expert with webpack.

**Comment by ashtonlance** [comment]
Any other updates or solutions to this? The lodash size is killing me.

**Comment by leo-coco** [comment]
Any news about it ? I'm using this on mobile and the size is becoming a real issue

**Comment by magicspon** [comment]
@leo-coco I'd suggest @kosmos suggestion!

**Comment by dobromir-hristov** [comment]
Yesterday I saw this exact issue as well. I am either switching to custom implementation or a leaflet one. Importing the whole lodash library is ridiculous in these days. At least load the lodash-es which can be treeshaked.

**Comment by xkjyeah** [comment]
Have you tried the other suggestions in this issue?

I know it's ridiculous, but the state of the JS standard library is
ridiculous too. Thanks.

**Comment by dobromir-hristov** [comment]
I use `babel-plugin-lodash`, but I think that doesnt work for deep dependency trees. Try importing lodash-es which is an ES6 module exported version. I think that can be tree shaked or the harder way to do it by importing single functions `import cloneDeep from lodash/cloneDeep` for example.

**Comment by xkjyeah** [comment]
um... if you've even considered rewriting the library, i'll actually invite you to just submit a PR. It should save you work.

If you figure out how to configure webpack, I could demo it in `examples/webpack.config.js`.

One hint if you choose this path: The reason the webpack plugin doesn't work for @magicspon is because used stubs. The stubs are for the web-distributable version of the package (i.e. where you can use &lt;script src="). I deliberately chose not to distribute lodash with it, but of course it then expects a global `_` to be available, which cannot be transformed by any plugin.

**Comment by dobromir-hristov** [comment]
Rollup is better for libraries. Webpack is more of a website thing. 
I will do a fork later today and see what I can do.
