### ISSUE TITLE
can't open windowInfo

### ISSUE THREAD

**Issue by stephanedemotte** [xkjyeah/vue-google-maps#9]
First: Thanks a lot for the Vue2 version :)

i can't open the infoWindow if i click on the marker, do you know how to fix it ?

repro
[link](http://xkjyeah.github.io/vue-google-maps/all-components.html)

Create a marker with right click, close it, and try to reopen.

**Comment by xkjyeah** [comment]
(repost) You have to listen for the marker_clicked event and then toggle
the marker's opened property.

Reason for this is that it becomes difficult to determine who controls the
opened property. Is it the parent marker? The marker (via close_clicked)?
The template? Moreover because two-way binding is no longer available it is
impossible to update each of the multiple controllers of changes to the
property. Hence click-to-open has been removed.
