### ISSUE TITLE
You have included the Google Maps API multiple times on this page. This may cause unexpected errors.

### ISSUE THREAD

**Issue by oppianmatt** [xkjyeah/vue-google-maps#92]
If you use this library in multiple independent components it will load the google maps library for each one.

Is there a way to check if VueGoogleMaps.load has already ran?

**Comment by oppianmatt** [comment]
actually think this was also a systemjs issue :(
tested with script tags and it was fine with multiple components

**Comment by maxschulmeister** [comment]
is there a fix for this?

**Comment by xkjyeah** [comment]
Do you have a test case reproducing the issue?

**Comment by wmcmurray** [comment]
I have this same error because the API is already loaded via a script tag in my page's HTML. And there is no way for me to tell this component "use this already loaded API instead of loading a new one" :frowning_face:

Solved it by not appending the script tag when in a page that loads this vuejs component.
