### ISSUE TITLE
Polygon "path" prop does not support MVCArray

### ISSUE THREAD

**Issue by noevidenz** [xkjyeah/vue-google-maps#97]
When editing a GmapPolygon, the `@path_changed` event passes the updated path as an MVCArray. 

Attempting to update the bound `:path` prop will cause an error due to an unexpected prop type (expects Array, receives Object).

This can be worked around by calling `path.getArray()` and assigning the result into the `:path` prop, however doing so breaks the undo functionality built into Google Maps when editing polygons.

**Comment by xkjyeah** [comment]
There's no easy way around this, except:

```html
<button @click="save()">Save</button>
<GmapMap>
<GmapPolygon :path="path" @path_changed="modifiedPath = $event"/>
</GmapMap>
```

```js
export default {
    data () {
        return {path: [...], modifiedPath: null}
    },
    methods: {
        save () {
            // FORCIBLY PURGE THE STATE ON THE EDITABLE POLYGON
            this.path = convertMVCToArray(this.modifiedPath)
        }
    }
}
```

The idea behind this is to avoid running the conversion function too frequently, as it might be a rather expensive operation, and you potentially lose the state at each point.

This is like listening for changes on an &lt;input> element, but instead of @input you only listen for events @change.

**Comment by xkjyeah** [comment]
Won't fix because for performance reasons, Google Maps API mutates the array, but Vue wouldn't like that.
